### ISSUE TITLE
package.json dependecies recursion

### ISSUE THREAD

**Issue by forgotPassword** [rootslab/spade#1]
spade -> vapid -> spade

**Comment by rootslab** [comment]
Do you have any problem installing spade?
It's not a circular dependency, __Spade__ use __Vapid__ only as a _devDependency_, then __only for tests__. It's the same for Vapid, it uses Spade for its tests.

**Comment by forgotPassword** [comment]
your install notes, say "npm install" which tries to install dev deps, which loops forever.

**Comment by rootslab** [comment]
[Travis build](https://travis-ci.org/rootslab/spade/jobs/49477881) I don't see any error installing.

**Comment by forgotPassword** [comment]
right, the problem is with --dev.
i guess it's npm quirk npm/npm#5554.

**Comment by rootslab** [comment]
You are right, docs are outdated.
Npm Docs: _"By default, **npm install** will install all modules listed as dependencies. With the **--production** flag, npm will not install modules listed in **devDependencies**."_

**Comment by rootslab** [comment]
Modified in b8fb1584d45a0b793a217a35ae07084046946bc8.
