### ISSUE TITLE
Replication support?

### ISSUE THREAD

**Issue by ben-lin** [rootslab/spade#2]
Hi, does `spade` supports replication? I can't seem to find it in the doc. 

Thanks!
Ben

**Comment by rootslab** [comment]
Did you mean [Redis Replication](http://redis.io/topics/replication)?
It's a matter of Redis configuration, to configure it on a running instance, you can use SLAVEOF or CONFIG SET commands [Syllabus](https://github.com/rootslab/syllabus#server). 
AFAIK, there is no module built upon spade to handle master/slave replication.

**Comment by ben-lin** [comment]
Thanks!

**Comment by rootslab** [comment]
;)
